### ISSUE TITLE
"This version of SemanticFormsSelect is only compatible with Semantic Forms 2.8 or above"

### ISSUE THREAD

**Issue by Rudloff** [SemanticMediaWiki/SemanticFormsSelect#43] opened 2016-11-28 21:58 UTC
When using SFS 1.3 with SF 3.7 and MW 1.28, I get this error:
```
Error: This version of SemanticFormsSelect is only compatible with Semantic Forms 2.8 or above. You need to upgrade Semantic Forms first.
```

It used to work correctly with MW 1.26 and seems to work again if I downgrade SF to 3.3.2.

**Comment by kghbln** [comment] 2016-11-28 22:07
This is indeed an utter mess. Let's count this as a dupe of https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/5

**Closed** 2016-11-28 22:10 UTC
Labels: bug, duplicate

**Comment by kghbln** [comment] 2016-11-28 22:20
@Rudloff I have just installed master of SFS together with master of PF on [sandbox](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version) and the issue no longer appears. Have not tested the functionality of this extension but most probably you would like to give it a go too.

**Comment by Rudloff** [comment] 2016-11-28 22:28
You're right, I can't reproduce this error with the latest master.
However I get other errors when trying to use forms that prevents me from using this version.
I will stay on 3.3.2/1.3 for now.

**Comment by kghbln** [comment] 2016-11-28 22:33
> However I get other errors when trying to use forms that prevents me from using this version.

@Rudloff Leaving the issues you already reported an created pull requests for left aside at the moment: Are these issues which need to be reported for and addressed with SFS? Or are other extensions like PF causing this?

**Comment by Rudloff** [comment] 2016-11-28 22:35
I get some JS errors with forms. I will try to see where they come from when I have some time.

**Comment by kghbln** [comment] 2016-11-28 22:37
> I get some JS errors with forms. I will try to see where they come from when I have some time.

This will be great. Thanks a lot!
