### ISSUE TITLE
parametrised query only fires on newly created pages

### ISSUE THREAD

**Issue by JosefAssad** [SemanticMediaWiki/SemanticFormsSelect#7] opened 2016-01-13 22:44 UTC
I'm sitting looking at a bit of an odd phenomenon. I have a couple of fields in a form, the second one populates a combobox based on the value of the first. Fairly standard.

It works fine when I create a new page using this form, and I can see the queries fire in the apache log.

when I use the "edit with form" tab on an existing page, the queries do not fire and the dependent field doesn't get populated.

Any clues? Happy to provide any and all debug info.

Versions:

MW: 1.24.4
SMW: 2.3
SF: 3.4.1
SFS: 1.3.0

**Comment by mariushart** [comment] 2016-02-02 08:59
What happens if you do an  "edit with form" and then CTRL + F5 ?

**Comment by JosefAssad** [comment] 2016-02-02 10:57
Same problem.

**Comment by fellam** [comment] 2016-02-11 11:37
Folks,
facing the same issue on a clean MW 1.26+ installation. 
I though this might help on finding and appropriate fix for this issue: 

after few debugs I realized that the root cause was that the missing load of the module **ext.sf_select.scriptselect** on _formedit action_.

The SemanticForms extension loads its modules in extensions/SemanticForms/includes/SF_Utils.php referring to the global _$wgOut_ class.

The SemanticFormsSelect eventually loads the module with a static call within the function Select of the class src/SemanticFormsSelect.php:
 `Output::addModule( 'ext.sf_select.scriptselect' );`

As workaround you use the global $wgOut to load the module and it will work:
on src/SemanticFormsSelect.php search for "Output::addModule( 'ext.sf_select.scriptselect' );"
and replace it with:
```
// fellam: workaround handling not loaded module in edit with form
global $wgOut;
$output->addModules( 'ext.sf_select.scriptselect' );
//Output::addModule( 'ext.sf_select.scriptselect' );
```

This works for me.

Wondering if there is a problem on "Output::addModule" which might be further investigated.. but no time to check now..

**Comment by JosefAssad** [comment] 2016-02-11 12:36
Confirmed workaround works, but @fellam I think when you write `$output->addModules( 'ext.sf_select.scriptselect' );` you mean `$wgOut->addModules( 'ext.sf_select.scriptselect' );`.

**Comment by fellam** [comment] 2016-02-11 13:08
Right.. there were some line missing from my original workaround, as you I will skip them for now, I will also update my previous comment. 
Thanks.

NOTE:
My code was actually:
```
global $wgOut; 
**$output=$wgOut;**
$output->addModules( 'ext.sf_select.scriptselect' );
```

This because SF_Utils.php is also handling wether or not the form is embedded in another page.
The original code would be:
```
global $wgOut;
if ( !$parser ) {
 $wgOut->addMeta( 'robots', 'noindex,nofollow' );
 $output = $wgOut;
} else {
 $output = $parser->getOutput();
}
$output->addModules( 'ext.sf_select.scriptselect' );
```

which brings to a note for whom will apply the fix: should we also handle this in the workaround retrieving the $parser?

Thanks

**Comment by kghbln** [comment] 2016-02-11 14:25
@toniher I am not sure if you are aware of this. Perhaps you may help. Cheers

**Comment by mwjames** [comment] 2016-02-11 14:57
Can someone make a PR for this?

How about to leaving the `Output` call as it is and instead extend it internals with
https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/src/Output.php#L50-L60

```
$parserOutput->addModules( array_values( self::$resourceModules ) );
$GLOBALS['wgOut']->addModules( array_values( self::$resourceModules ) );
```

> which brings to a note for whom will apply the fix: should we also handle this in the workaround retrieving the $parser?

No need.

`Output::addModule( 'ext.sf_select.scriptselect' );` registers the module and `Output::commitToParserOutput( $this->parser->getOutput() );` is using the parser invoked.

Given the change above, maybe renaming `Output::commitToParserOutput` to `Output::commit`.

**Comment by Rudloff** [comment] 2016-07-23 22:06
Here is a simple workaround that you can add to your `LocalSettings.php` file:
```php
$wgExtensionFunctions[] = function () {
    global $wgOut;
    $wgOut->addModules('ext.sf_select.scriptselect');
};
```

**Comment by gesinn-it** [comment] 2016-12-19 15:43
MW 1.27.x
SMW 2.4.x
PF 4.0.2
SFS @dev

Non of the workarounds suggested by @mwjames or @Rudloff works for me. 'ext.sf_select.scriptselect' seems to be never loaded (cleared browser caches, restarted web server...).

**Comment by gesinn-it** [comment] 2016-12-19 15:52
I think there should be a ResourceModules definition in extension.json [1]. I'll try this.

[1] https://www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader#Registering

**Comment by kghbln** [comment] 2016-12-20 11:18
> I think there should be a ResourceModules definition in extension.json [1]. I'll try this.

If this worked out a patch is welcome.

**Comment by Rudloff** [comment] 2016-12-20 11:45
Are you sure this is still an issue? The script does work for me with MW 1.28.0, SFS 2.0.0 and PF 4.0.2 (and without my previous workaround).

**Comment by gesinn-it** [comment] 2016-12-20 11:54
I can confirm that it is working with the latest releases without any issues. I think this can be closed.

**Comment by kghbln** [comment] 2016-12-20 12:29
@Rudloff @gesinn-it Thanks a lot for you feedback. Cool that this one was fixed somehow en passant.

**Closed by kghbln** 2016-12-20 12:29 UTC
Labels: bug
